---
# Critical parameters for preprocessing pipeline
preprocessing_parameters:
  SEED: 1234
  MAX_VOCAB_SIZE: 25_000
  BATCH_SIZE: 64
  train_path: data\Train.csv
  test_path: data\Valid.csv
  vectors: glove.6B.100d
  deterministic: True
  tokenizer: spacy
  tokenizer_language: en_core_web_sm

# Critical parameters for model construction
model_parameters:
  EMBEDDING_DIM: 100
  HIDDEN_DIM: 256
  OUTPUT_DIM: 1
  N_LAYERS: 2
  BIDIRECTIONAL: True
  DROPOUT: 0.5
  N_EPOCHS: 3
  model_dict_name: 2_layers_dict.pt
  model_name: 2_layers.pt
  model_dir: model
  chart_dir: charts

# Critical parameters to save progress
persistence_parameters:
  vocab_dir: vocab
  vocab_filename: TEXT
